---
kind: pipeline
type: docker
name: TESTING

platform:
  os: linux
  arch: amd64


steps:
  - name: test
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn test

---
kind: pipeline
type: docker
name: build-push-dockerhub

platform:
  os: linux
  arch: amd64

steps:
  - name: lint_dockerfiles
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint src/main/docker/Dockerfile.jvm
      - hadolint src/main/docker/Dockerfile.legacy-jar
      - hadolint src/main/docker/Dockerfile.native
      - hadolint src/main/docker/Dockerfile.native-micro


trigger:
  branch:
    - main
  event:
    - pull_request


