kind: pipeline
type: docker
name: default

trigger:
  event:
    - push

steps:
  - name: greeting
    image: alpine
    commands:
      - echo Hello
      - echo World
---
kind: pipeline
type: docker
name: deployment

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - promote
    - tag

steps:
  - name: deployment
    image: pelotech/drone-helm3
    commands: 
      - echo "Tag or Promote event trigger"
      - echo "Version to deploy ${VERSION}"