---
kind: pipeline
type: docker
name: default

trigger:
  event:
    - push
  
steps:
  - name: greeting
    image: alpine
    commands:
      - echo "Greeting Step and hello !"
  - name: morehello
    image: alpine
    commands:
      - echo Hello
      - echo World

---
kind: pipeline
type: docker
name: search_for_quay_tag
steps:
  - name: greeting
    image: alpine
    commands:
      - echo "Some Test Here"
  - name: Search tag
    image: alpine
    commands: 
    - apk update
    - apk upgrade
    - apk add curl
    - curl http://google.com
    - |
      if curl -v --silent https://quay.io/api/v1/repository/ukhomeofficedigital/engineering-guidance-and-standards/tag/ 2>&1 | grep latest; then
        echo "Tag found. Exiting with code 0"
        exit 0
      else
          echo "Tag not found waiting ..."
          sleep 20s
      fi
    
---
kind: pipeline
type: docker
name: deployment

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - promote
    - tag

steps:
  - name: Lint-Helm-Chart
    image: pelotech/drone-helm3
    settings:
      mode: lint
      chart: helm
      values_files: helm/values.yaml
      values:
      - image.tag=latest

  - name: deployment
    image: pelotech/drone-helm3
    settings:
      chart: helm
      mode: install
      namespace: default
      release: cto-dashboard
      kube_certificate:
        from_secret: kube_certificate
      kube_api_server: 
        from_secret: kube_api_server
      kube_token:
        from_secret: kube_token
      values_files: helm/values.yaml
      wait_for_upgrade: true
      timeout: 10m
      debug: true
      values:
      - image.tag=latest
    commands: 
      - echo "Tag or Promote event trigger"
      - echo "Version to deploy ${VERSION}"