kind: pipeline
type: docker
name: default

steps:
  - name: greeting
    image: alpine
    commands:
      - echo Hello
      - echo World
---
kind: pipeline
type: kubernetes
name: deployment

platform:
  os: linux
  arch: amd64

trigger:
  event:
    - promote
    - tag

steps:
  - name: deploy
    image: alpine
    commands: 
      - echo Tag or Promote event trigger
      - echo "Version to deploy ${VERSION}"