#---
#kind: pipeline
#type: docker
#name: TESTING
#
#platform:
#  os: linux
#  arch: amd64
#
#
#steps:
#  - name: test
#    image: maven:3.8.3-openjdk-17
#    commands:
#      - mvn test

---
kind: pipeline
type: docker
name: build-push-dockerhub

platform:
  os: linux
  arch: amd64

steps:
  - name: lint_dockerfiles
    pull: if-not-exists
    image: hadolint/hadolint:latest-alpine
    commands:
      - hadolint src/main/docker/Dockerfile.jvm
      - hadolint src/main/docker/Dockerfile.legacy-jar
      - hadolint src/main/docker/Dockerfile.native
      - hadolint src/main/docker/Dockerfile.native-micro

  - name: package_quarkus_app
    image: maven:3.8.3-openjdk-17
    commands:
      - mvn package -Dquarkus.package.type=legacy-jar

  - name: build-and-push-image
    image: plugins/docker
    depends_on:
      - package_quarkus_app
    settings:
      username: sever3d
      password:
        from_secret: docker_hub_pwd # Configure the secret in the Drone repository setting
      repo: sever3d/quarkus-drone-demo
      tags: 0.0.1
      dockerfile: src/main/docker/Dockerfile.legacy-jar # Where the Dockerfile is located in your git repository


trigger:
  branch:
    - main
  event:
    - pull_request


