---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.project.name }}
spec:
  selector:
    app: {{ .Values.project.name }}
  type: ClusterIP
  ports:
  - port: {{ .Values.ports.servicePort }}
    targetPort: {{ .Values.ports.targetPort }}
    protocol: TCP