name: build-push-image-moja-akcja

on:
    push:
      branches:
        - main
        - 'task-**'

jobs:
    buildpush:
        name: 'Main Semver Tag'
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3

          - name: Set up JDK 17
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: 'adopt'
                
          - name: Build with Maven
            run: mvn --batch-mode --update-snapshots package

          - name: Publish image to Docker
            uses: severinum/github-workflows/.github/actions/docker-publish@v1
            with:
                registry: quay.io/sewerynmi
                username: ${{ secrets.DOCKER_USER_NAME || secrets.QUAY_ROBOT_USER_NAME }}
                password: ${{ secrets.DOCKER_PASSWORD || secrets.QUAY_ROBOT_TOKEN }}
                tag: happy
                tag_latest: ${{ github.base_ref == 'main' }}
                image: drone-demo
                docker_context: ./src/main/docker/Dockerfile.legacy-jar


    