name: build-publish-quay-and-tag

# on:
#   pull_request:
#     types: [ closed ]

on:
  push:
    branches:
      - main
      - 'task-**'
  
jobs:
  quay-login:
    name: Quay Login
    runs-on: ubuntu-latest
    steps:
      - name: Login to repository
        uses: docker/login-action@v2
        with:
          registry: 'quay.io'
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

  build_push_tag_repo:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-tag-docker.yml@v2
    with:
       image: quay.io/sewerynmi/drone-demo
    secrets: inherit
