# name: 'SemVer Tag Repo'
# on:
#   pull_request:
#     types: [ closed ]

# jobs:
#   build:
#     name: 'Build and Docker Push Tags'
#     runs-on: ubuntu-latest
#     steps:
#         - name: Checkout repository
#           uses: actions/checkout@v3
#         - name: Sleep for 3 minutes
#           run: sleep 5s
#           shell: bash

#   tag:
#     name: SemVer auto-tagging
#     runs-on: ubuntu-latest
#     needs: build 
#     if: |
#       github.event.pull_request.merged == true &&
#       contains(github.event.pull_request.labels.*.name, 'skip-release') == false
#     permissions:
#       packages: write
#       contents: read
#     steps:
#       - id: label
#         uses: UKHomeOffice/match-label-action@main
#         with:
#           labels: minor,major,patch
#           mode: singular

#       - name: Calculate SemVer value
#         id: calculate
#         uses: UKHomeOffice/semver-calculate-action@main
#         with:
#           increment: ${{ steps.label.outputs.matchedLabels }}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           default_to_highest: ${{ github.base_ref == 'main' }}

#       - name: Tag Repository
#         uses: UKHomeOffice/semver-tag-action@main
#         with:
#           tag: ${{ steps.calculate.outputs.version }}
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           move_major_tag: false