name: build-publish-quay-and-tag

on:
  pull_request:
    types: [ closed ]
  
jobs:
  quay-login:
    name: Quay Login
    runs-on: ubuntu-latest
    steps:
      - name: Login to repository
        uses: docker/login-action@v2
        with:
          registry: 'quay.io'
          username: ${{ secrets.QUAY_ROBOT_USER_NAME }}
          password: ${{ secrets.QUAY_ROBOT_TOKEN }}

  build:
    uses: UKHomeOffice/sas-github-workflows/.github/workflows/semver-tag-docker.yml@v2
    with:
       registry: 'quay.io'
       image: 'quay.io/sewerynmi/drone-demo'
       ecr: false
    secrets: inherit
